### PR TITLE
food purple

### PR DESCRIPTION
**Pull request by ryanwmichaud**
or water I actually don't remember

### CODE REVIEW

**Comment by wknowleskellett** [comment]
Was there a reason you wanted food to be purple? There should be a reason for any pull request. That doesn't preclude changes based on preference; in that case the reason is that the group agrees on the change.

**Comment by AjaiKN** [comment]
I wasn't the person who made this pull request, but I don't think it's a problem that it was made, even if the group hasn't agreed on the change. Not every pull request needs to be merged.

Sure, ideally, maybe you should have a club consensus before you implement something. But with a change as tiny as this and a club as small/informal as this, I think a pull request is a great way to try out a change and see what the club thinks. It's also a good learning experience, even if you wouldn't want to do it with a more serious project.

**Comment by wknowleskellett** [comment]
That's fair. That granted, I think the pull request should include a note. Here are some examples of how low my bar is:

- Purple food contrasts better with the background
- Can we make food purple? (acknowledges that this is a discussion)
- Green food is vegetables. I feel bad that our critters are only ingesting vegetables and water. I propose: _purple_. Purple is new. Purple is interesting. Purple is ✨mysterious✨. Vote purple.

**Comment by AjaiKN** [comment]
Yeah, good point. I think that's reasonable.

**Comment by ryanwmichaud** [comment]
Hi! That was just me trying to learn how to make a pull request, I don't really think the food should be purple lol
I'll be sure to do that when I make one for real!

**Comment by wknowleskellett** [comment]
You did it! I'm so proud 😄
Note: There's a lot more exciting work to be done as we move to Unity [here](https://github.com/ObieSource/Genetics).

**Pull request closed without merging**
